### PR TITLE
code changes

### PR DESCRIPTION
**Pull request by mirsaidoff**

### CODE REVIEW

**Comment by mirsaidoff** [comment]
@AmrAbdelhameed made some improvements. review them :)

**Comment by AmrAbdelhameed** [comment]
@mirsaidoff I would like to thank you for your interest, improvements and contribution.

**Comment by AmrAbdelhameed** [comment]
@mirsaidoff I would like to thank you for your interest, improvements and contribution.

**Comment by mirsaidoff** [comment]
always welcome :)

**Pull request merged**
